<div class="container-xl px-3 py-4">
    <div class="d-flex flex-wrap justify-content-between align-items-center gap-3 mb-3">
        <div>
            <h1 class="h4 mb-1">Editorial Inbox</h1>
            <div class="text-muted small">Review, edit, approve, and publish articles generated by AI.</div>
        </div>

        <div class="d-flex gap-2 align-items-center">
            <a href="{{ url('/') }}" class="btn btn-outline-secondary btn-sm">View Site</a>
        </div>
    </div>

    <div class="card border-0 shadow-sm mb-3">
        <div class="card-body">
            <div class="row g-2 align-items-end">
                <div class="col-md-3">
                    <label class="form-label small text-muted mb-1">Status</label>
                    <select class="form-select form-select-sm" wire:model.live="status">
                        @foreach ($statusOptions as $value => $label)
                            <option value="{{ $value }}">{{ $label }}</option>
                        @endforeach
                    </select>
                </div>

                <div class="col-md-6">
                    <label class="form-label small text-muted mb-1">Search</label>
                    <input type="text" class="form-control form-control-sm"
                        placeholder="Search title, lead, or body..." wire:model.live.debounce.350ms="q">
                </div>

                <div class="col-md-3">
                    <label class="form-label small text-muted mb-1">Per Page</label>
                    <select class="form-select form-select-sm" wire:model.live="perPage">
                        <option value="10">10</option>
                        <option value="15">15</option>
                        <option value="25">25</option>
                        <option value="50">50</option>
                    </select>
                </div>
            </div>
        </div>
    </div>

    <div class="card border-0 shadow-sm">
        <div class="card-body p-0">
            <div class="table-responsive">
                <table class="table table-hover mb-0 align-middle">
                    <thead class="table-light">
                        <tr>
                            <th class="ps-3">Title</th>
                            <th>Status</th>
                            <th>Tags</th>
                            <th class="text-nowrap">Created</th>
                            <th class="text-end pe-3">Action</th>
                        </tr>
                    </thead>
                    <tbody>
                        @forelse($articles as $article)
                            <tr>
                                <td class="ps-3" style="min-width: 320px;">
                                    <div class="fw-semibold">{{ $article->title }}</div>
                                    <div class="text-muted small">
                                        {{ \Illuminate\Support\Str::limit(strip_tags($article->lead ?? ''), 110) }}
                                    </div>
                                </td>
                                <td class="text-nowrap">
                                    <span
                                        class="badge
                                        @if ($article->status === 'ai_draft') bg-secondary
                                        @elseif($article->status === 'needs_review') bg-warning text-dark
                                        @elseif($article->status === 'approved') bg-info text-dark
                                        @elseif($article->status === 'published') bg-success
                                        @elseif($article->status === 'rejected') bg-danger
                                        @else bg-light text-dark @endif
                                    ">
                                        {{ strtoupper(str_replace('_', ' ', $article->status)) }}
                                    </span>
                                </td>
                                <td style="min-width: 220px;">
                                    @if ($article->tags->count())
                                        <div class="d-flex flex-wrap gap-1">
                                            @foreach ($article->tags->take(6) as $tag)
                                                <span class="badge bg-light text-dark border">{{ $tag->name }}</span>
                                            @endforeach
                                            @if ($article->tags->count() > 6)
                                                <span
                                                    class="badge bg-light text-dark border">+{{ $article->tags->count() - 6 }}</span>
                                            @endif
                                        </div>
                                    @else
                                        <span class="text-muted small">—</span>
                                    @endif
                                </td>
                                <td class="text-nowrap">
                                    <span class="text-muted small">{{ $article->created_at->diffForHumans() }}</span>
                                </td>
                                <td class="text-end pe-3">
                                    <a href="{{ route('editor.articles.edit', $article) }}"
                                        class="btn btn-primary btn-sm">
                                        Open
                                    </a>
                                </td>
                            </tr>
                        @empty
                            <tr>
                                <td colspan="5" class="text-center py-5 text-muted">
                                    No articles found.
                                </td>
                            </tr>
                        @endforelse
                    </tbody>
                </table>
            </div>

            <div class="p-3">
                {{ $articles->links() }}
            </div>
        </div>
    </div>
</div>
